name: archlinux arm build nightly

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup variables
        run: |
          echo RELEASE=$(date +%Y\/%m\/%d) >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install make mkbootimg build-essential \
            libncurses5-dev bison flex libssl-dev device-tree-compiler \
            gcc-arm-none-eabi gcc-aarch64-linux-gnu bc libfdt-dev \
            libarchive-tools arch-install-scripts qemu-user-static

      - name: Initialization submodule
        run: git submodule update --init

      - name: Build packets
        run: sudo bash ${{github.workspace}}/build.sh

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          body: ${{env.RELEASE}}
          tag_name: ${{env.RELEASE}}
          draft: false
          prerelease: false
          files: |
            ${{github.workspace}}/build/aboot.img
            ${{github.workspace}}/build/boot.img
            ${{github.workspace}}/build/rootfs.img.zst
            ${{github.workspace}}/build/aboot.img.sha256sum
            ${{github.workspace}}/build/boot.img.sha256sum
            ${{github.workspace}}/build/rootfs.img.zst.sha256sum

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          keep_latest: 1
          delete_tags: true
